[package]
name = "iris_vm"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive", "rc"] }
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
zip = "0.6.6"
